Name: PRODUCTION
Type: FolderType
Children:
- Name: KPI01_PROD_C
  Type: BaseDataVariableType
  DataType: Color
  Value: "#e4e4e4"
  Children:
  - Name: ConditionalConverter1
    Type: ConditionalConverter
    Children:
    - Name: Condition
      Type: BaseDataVariableType
      DataType: Boolean
      ReferenceType: HasSource
      Children:
      - Name: ExpressionEvaluator1
        Type: ExpressionEvaluator
        Children:
        - Name: Expression
          Type: BaseDataVariableType
          DataType: String
          ReferenceType: HasParameter
          Value: "{0}<0.00014"
        - Name: ns=3;Source0
          Type: BaseDataVariableType
          DataType: BaseDataType
          ReferenceType: HasSource
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../../../../KPIS/ESG/KPI_ESG_001 ENV iNTENSITY"
    - Name: TrueValue
      Type: BaseDataVariableType
      DataType: Color
      ReferenceType: HasParameter
      Value: "#27ae60"
    - Name: FalseValue
      Type: BaseDataVariableType
      DataType: Color
      ReferenceType: HasParameter
      Value: "#ffffff"
      Children:
      - Name: ConditionalConverter1
        Type: ConditionalConverter
        Children:
        - Name: Condition
          Type: BaseDataVariableType
          DataType: Boolean
          ReferenceType: HasSource
          Children:
          - Name: ExpressionEvaluator1
            Type: ExpressionEvaluator
            Children:
            - Name: Expression
              Type: BaseDataVariableType
              DataType: String
              ReferenceType: HasParameter
              Value: "{0}>=0.00014&&{0}<=0.00015"
            - Name: ns=3;Source0
              Type: BaseDataVariableType
              DataType: BaseDataType
              ReferenceType: HasSource
              Children:
              - Name: DynamicLink
                Type: DynamicLink
                DataType: NodePath
                Value: "../../../../../../../../../KPIS/ESG/KPI_ESG_001 ENV iNTENSITY"
        - Name: TrueValue
          Type: BaseDataVariableType
          DataType: Color
          ReferenceType: HasParameter
          Value: "#f8e71c"
        - Name: FalseValue
          Type: BaseDataVariableType
          DataType: Color
          ReferenceType: HasParameter
          Value: "#eb001b"
- Name: KPI02_PROD_C
  Type: BaseDataVariableType
  DataType: Color
  Value: "#e4e4e4"
- Name: KPI03_PROD_C
  Type: BaseDataVariableType
  DataType: Color
  Value: "#e4e4e4"
- Name: KPI04_PROD_C
  Type: BaseDataVariableType
  DataType: Color
  Value: "#e4e4e4"
