Name: Producción
Type: FolderType
Children:
- Name: Ley_mineral_entrada
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Ley_mineral_entrada_Molienda"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Ley_mineral_salida
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Ley_mineral_salida_Molienda"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Disponibilidad_Molino
  Type: BaseDataVariableType
  DataType: Int32
- Name: Rendimiento_Molino
  Type: BaseDataVariableType
  DataType: Int32
- Name: Calidad_Molino
  Type: BaseDataVariableType
  DataType: Int32
