Name: Producción
Type: FolderType
Children:
- Name: Ley_mineral_entrada
  Type: BaseDataVariableType
  DataType: Float
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Ley_mineral_entrada_chan"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Ley_mineral_salida
  Type: BaseDataVariableType
  DataType: Float
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Ley_mineral_salida_proceso"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Disponibilidad
  Type: BaseDataVariableType
  DataType: Float
- Name: Rendimiento
  Type: BaseDataVariableType
  DataType: Float
- Name: Calidad
  Type: BaseDataVariableType
  DataType: Float
- Name: Costo_total
  Type: BaseDataVariableType
  DataType: Float
- Name: Toneladas_producidas
  Type: BaseDataVariableType
  DataType: Float
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Toneladas_producidas_totales_proceso"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: 'KPI_PROD_001 PRODUCTION '
  Type: BaseDataVariableType
  DataType: Float
- Name: KPI_PROD_002 RECOVERY
  Type: BaseDataVariableType
  DataType: Float
- Name: KPI_PROD_003 OEE
  Type: BaseDataVariableType
  DataType: Float
- Name: KPI_PROD_004 COSTS PER TON
  Type: BaseDataVariableType
  DataType: Float
