Name: Producción
Type: FolderType
Children:
- Name: Cu_Teorico_kg
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Cu_Teorico_Kg"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Cu_Real_kg
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Cu_Real_kg"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Ley_mineral_entrada
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Ley_Anodo_entrada_pct"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Ley_mineral_salida
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Ley_Catodo_salida_pct"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Toneladas_producidas_electro
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Toneladas_catodos_producidos"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: rendimiento
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/rendimiento_tanque_electro"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: calidad
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/RAEtherNet_IPDriver1/RAEtherNet_IPStation1/Tags/Controller Tags/Calidad_tanque_electro"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
